env_args:
    env_name: IceHockey-ram-v0
    env_type: gym
    num_envs: 4
    seed: random

agent_args:
    algorithm: PPO
    algorithm_spec:
        episodic_update: True  # as PPO is on-policy, it uses episodic update instead of update per timestep
        gamma: 0.99
        lambda: 0.95
        eps_clip: 0.2
        K_epoch: 4
        GAE: True  # generalized advantage estimation

train_args:
    max_episodes: 10000
    max_steps_per_episode: 10000
    train_start_frame: 0
    optimizer: adam
    learning_rate: 1e-4
    device: gpu
    log_avg_window: 20 # average window length in logging
    log_interval: 20  # log print interval 
    # render: True
    net_architecture:   
        policy:
            hidden_dim_list: [64, 64, 64]  
            hidden_activation: Tanh
            output_activation: Softmax
        value:
            hidden_dim_list: [64, 64, 64]  
            hidden_activation: Tanh
            output_activation: False