env_args:
  env_name: SlimeVolley-v0
  env_type: slimevolley
  num_envs: 2
  against_baseline: false
  ram: true
  seed: random
agent_args:
  algorithm: NashPPO
  algorithm_spec:
    episodic_update: true
    gamma: 0.99
    lambda: 0.95
    eps_clip: 0.2
    K_epoch: 4
    GAE: true
train_args:
  batch_size: 32
  max_episodes: 10000
  max_steps_per_episode: 10000
  train_start_frame: 0
  optimizer: adam
  learning_rate: 1e-4
  device: gpu
  update_itr: 1
  log_avg_window: 20
  log_interval: 20
  multiprocess: false
  net_architecture:
    policy:
      hidden_dim_list:
      - 64
      - 64
      - 64
      - 64
      hidden_activation: ReLU
      output_activation: Softmax
    value:
      hidden_dim_list:
      - 64
      - 64
      - 64
      - 64
      hidden_activation: ReLU
      output_activation: false
  marl_spec:
    global_state: true
  marl_method: nash_ppo
