env_args:
  env_name: space_war_v1
  env_type: pettingzoo
  num_envs: 2
  ram: true
  seed: random
agent_args:
  algorithm: NashDQNExploiter
  algorithm_spec:
    dueling: false
    replay_buffer_size: 1e5
    gamma: 0.99
    multi_step: 1
    target_update_interval: 1000
    eps_start: 1.0
    eps_final: 0.01
    eps_decay: 30000
    exploiter_update_itr: 3
train_args:
  batch_size: 128
  max_episodes: 10000
  max_steps_per_episode: 10000
  train_start_frame: 0
  optimizer: adam
  learning_rate: 1e-4
  device: gpu
  update_itr: 1.0
  log_avg_window: 20
  log_interval: 20
  multiprocess: false
  net_architecture:
    hidden_dim_list:
    - 128
    - 128
    - 128
    - 128
    hidden_activation: ReLU
    output_activation: false
  marl_method: nash_dqn_exploiter
  marl_spec:
    global_state: false
