wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    code_path: code/general_train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1657162218
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 35
      4: 3.7.0
      5: 0.12.18
      8:
      - 5
algorithm:
  desc: null
  value: NashPPO
algorithm_spec:
  desc: null
  value:
    GAE: true
    K_epoch: 4
    dueling: false
    entropy_coeff: 0.01
    episodic_update: true
    eps_clip: 0.2
    eps_decay: 30000
    eps_final: 0.001
    eps_start: 1.0
    gamma: 0.99
    lambda: 0.95
    max_grad_norm: 0.5
    multi_step: 1
    policy_loss_coeff: 0.08
    replay_buffer_size: 1e5
    target_update_interval: 1000
    vf_coeff: 0.5
batch_size:
  desc: null
  value: 128
device:
  desc: null
  value: gpu
env_name:
  desc: null
  value: boxing_v2
env_type:
  desc: null
  value: pettingzoo
eval_models:
  desc: null
  value: false
exploit:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 1e-4
load_model_full_path:
  desc: null
  value: false
load_model_idx:
  desc: null
  value: false
log_avg_window:
  desc: null
  value: 20
log_interval:
  desc: null
  value: 20
marl_method:
  desc: null
  value: nash_ppo
marl_spec:
  desc: null
  value:
    global_state: true
    min_update_interval: 20
    score_avg_window: 10
max_episodes:
  desc: null
  value: 10000
max_steps_per_episode:
  desc: null
  value: 300
multiprocess:
  desc: null
  value: false
net_architecture:
  desc: null
  value:
    feature:
      channel_list:
      - 32
      - 64
      - 64
      hidden_activation: ReLU
      hidden_dim_list:
      - 512
      kernel_size_list:
      - 8
      - 4
      - 3
      output_activation: false
      stride_list:
      - 4
      - 2
      - 1
    hidden_activation: ReLU
    hidden_dim_list:
    - 128
    - 128
    - 128
    output_activation: false
    policy:
      hidden_activation: false
      hidden_dim_list:
      - 512
      output_activation: Softmax
    value:
      hidden_activation: ReLU
      hidden_dim_list:
      - 512
      output_activation: false
num_envs:
  desc: null
  value: 5
num_process:
  desc: null
  value: 1
optimizer:
  desc: null
  value: adam
ram:
  desc: null
  value: false
record_video:
  desc: null
  value: false
render:
  desc: null
  value: false
save_id:
  desc: null
  value: 0
save_interval:
  desc: null
  value: 2000
save_path:
  desc: null
  value: ''
seed:
  desc: null
  value: random
test:
  desc: null
  value: false
train_start_frame:
  desc: null
  value: 0
update_itr:
  desc: null
  value: 1
wandb_activate:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: quantumiracle
wandb_group:
  desc: null
  value: ''
wandb_name:
  desc: null
  value: '0'
wandb_project:
  desc: null
  value: pettingzoo_boxing_v2_nash_ppo
